package skillgen

import (
	"bufio"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"net/url"
	"path/filepath"
	"sort"
	"strings"
)

// bundledContent holds every skill shipped in the CLI binary. These files are
// GENERATED byte-identical mirrors of the single human-authored source at
// skills/<name>/SKILL.md (repo root); do not hand-edit them. `go:embed` cannot
// reach outside the cli/ Go module, so the source is mirrored into this tree by
// `make skills` (tools/skills_sync.py) and pinned to the source by the drift
// test (tests/arch/test_skill_drift.py). The backend ships the same bytes and
// serves them at `GET /skills/<name>.md` (#651). A single-file string/[]byte
// target can only hold one file, so the multi-skill set requires an embed.FS.
//
//go:generate sh -c "cd ../../.. && make skills"
//go:embed content/*.md
var bundledContent embed.FS

//go:embed content/tasks
var taskSkillsFS embed.FS

// bundledDir is the embed sub-path the skill markdown files live under.
const bundledDir = "content"

// Skill kinds. "canonical" is the structured jentic skill (parsed into
// sections/steps); "freeform" is a runbook whose body is emitted verbatim.
const (
	KindCanonical = "canonical"
	KindFreeform  = "freeform"
)

// BundledNames returns the names of every bundled skill (the embed dir entries
// with the .md suffix stripped), sorted for a stable order. This is the single
// source of truth for the shipped set — there is no hand-maintained list.
func BundledNames() []string {
	entries, err := fs.ReadDir(bundledContent, bundledDir)
	if err != nil {
		// The content dir is compiled in via go:embed, so a read error is a
		// build-time programming error, not a runtime condition.
		return nil
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name, ok := strings.CutSuffix(e.Name(), ".md")
		if !ok {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// contentFor reads the raw bundled markdown for one skill name.
func contentFor(name string) (string, error) {
	data, err := bundledContent.ReadFile(bundledDir + "/" + name + ".md")
	if err != nil {
		return "", fmt.Errorf("read bundled skill %q: %w", name, err)
	}
	return string(data), nil
}

// Bundled parses the named embedded skill into a Canonical, stamping the
// resolved control-plane base URL and bundled provenance into it. A malformed
// embed is a build-time programming error (the content is compiled into the
// binary and covered by tests), so this should never fail at runtime — but it
// returns an error rather than panicking so a CLI command surfaces it cleanly
// instead of crashing.
func Bundled(name, baseURL string) (Canonical, error) {
	if err := validateBaseURL(baseURL); err != nil {
		return Canonical{}, err
	}
	src, err := contentFor(name)
	if err != nil {
		return Canonical{}, err
	}
	c, err := parseSkill(src)
	if err != nil {
		return Canonical{}, fmt.Errorf("parse bundled skill %q: %w", name, err)
	}
	c.BaseURL = baseURL
	c.Origin = SourceBundled
	return c, nil
}

// validateBaseURL rejects a control-plane base URL that could break out of a
// managed block or corrupt an AGENTS.md when interpolated. The base URL is
// stamped verbatim into the rendered body (canonical) and the AGENTS.md pointer
// link (all operators); a value containing a newline or a marker fragment could
// otherwise inject a forged BEGIN/END sentinel, so a later findBlock binds to
// the wrong region and a subsequent update/remove strands attacker text as
// free content in a file we promise to edit-preserve. We fail closed: an empty
// base URL is allowed (adapters simply omit the link line), but any newline,
// other control character, HTML-comment fence, or the marker phrase is refused,
// and the value must be an http(s) URL. This is the single choke point through
// which every BaseURL enters skillgen, so no caller can bypass it.
func validateBaseURL(baseURL string) error {
	if baseURL == "" {
		return nil
	}
	if i := strings.IndexFunc(baseURL, func(r rune) bool { return r < 0x20 || r == 0x7f }); i >= 0 {
		return fmt.Errorf("invalid base URL %q: contains a control character", baseURL)
	}
	if strings.Contains(baseURL, "<!--") || strings.Contains(baseURL, "-->") ||
		strings.Contains(baseURL, "MANAGED SKILL") {
		return fmt.Errorf("invalid base URL %q: contains managed-block marker text", baseURL)
	}
	u, err := url.Parse(baseURL)
	if err != nil {
		return fmt.Errorf("invalid base URL %q: %w", baseURL, err)
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return fmt.Errorf("invalid base URL %q: scheme must be http or https", baseURL)
	}
	return nil
}

// BundledSet loads every bundled skill (in BundledNames order), stamping each
// with the resolved base URL and bundled provenance.
func BundledSet(baseURL string) ([]Canonical, error) {
	names := BundledNames()
	set := make([]Canonical, 0, len(names))
	for _, name := range names {
		c, err := Bundled(name, baseURL)
		if err != nil {
			return nil, err
		}
		set = append(set, c)
	}
	return set, nil
}

// parseSkill reads a skill markdown file into a Canonical. The kind is read
// explicitly from `metadata.kind` in the frontmatter (defaulting to
// "canonical" for the jentic skill's back-compat) — it is never inferred from
// which H2 headings happen to be present. Freeform skills require only
// `name`+`description` and carry their verbatim body; canonical skills keep the
// structured section parse (WhenToUse/Prereqs/Steps/…).
func parseSkill(src string) (Canonical, error) {
	c := Canonical{Version: "1", Kind: KindCanonical}

	body, fm := splitFrontmatter(src)
	for k, v := range fm {
		switch k {
		case "name":
			c.Name = v
		case "description":
			c.Description = v
		case "version":
			c.Version = v
		case "metadata.kind":
			if v != "" {
				c.Kind = v
			}
		case "metadata.argument-hint":
			c.ArgumentHint = unquoteYAML(v)
		}
	}

	if c.Name == "" {
		return c, errors.New("missing name in frontmatter")
	}
	if c.Description == "" {
		return c, errors.New("missing description in frontmatter")
	}

	if c.Kind == KindFreeform {
		// Freeform skills are emitted verbatim: the whole markdown body after
		// the frontmatter is the skill content. Do not run the section parser.
		c.Body = strings.TrimRight(body, "\n") + "\n"
		return c, nil
	}

	sections := splitSections(body)
	c.WhenToUse = bullets(sections["When to Use"])
	c.Prereqs = bullets(sections["Prerequisites"])
	c.QuickRef = bullets(sections["Quick Reference"])
	c.Pitfalls = bullets(sections["Pitfalls"])
	c.Verify = bullets(sections["Verification"])
	c.Steps = parseSteps(sections["Procedure"])

	if len(c.Steps) == 0 {
		return c, errors.New("no procedure steps found")
	}
	return c, nil
}

// unquoteYAML strips a single pair of matching surrounding quotes from a scalar
// value (argument-hint is authored as `"…"` in the frontmatter).
func unquoteYAML(v string) string {
	if len(v) >= 2 {
		if (v[0] == '"' && v[len(v)-1] == '"') || (v[0] == '\'' && v[len(v)-1] == '\'') {
			return v[1 : len(v)-1]
		}
	}
	return v
}

// splitFrontmatter separates a leading `---`-delimited YAML block from the
// markdown body. It reads flat `key: value` pairs and, additionally, a single
// nested `metadata:` block: indented `  kind:` / `  argument-hint:` children
// are captured under the dotted keys `metadata.kind` / `metadata.argument-hint`
// so the caller can read them without a full YAML parser. The closing fence is
// only honored as a line that is exactly `---`, so a `---` thematic break or
// YAML embedded in the body does not truncate the frontmatter early.
func splitFrontmatter(src string) (body string, fm map[string]string) {
	fm = map[string]string{}
	s := strings.TrimLeft(src, "\n")
	if !strings.HasPrefix(s, "---\n") {
		return src, fm
	}
	rest := s[len("---\n"):]
	fenceStart, fenceEnd := closingFence(rest)
	if fenceStart < 0 {
		return src, fm
	}
	inMetadata := false
	for _, line := range strings.Split(rest[:fenceStart], "\n") {
		// A nested block child: an indented `key: value` under `metadata:`.
		if inMetadata && (strings.HasPrefix(line, "  ") || strings.HasPrefix(line, "\t")) {
			k, v, ok := strings.Cut(strings.TrimSpace(line), ":")
			if !ok {
				continue
			}
			fm["metadata."+strings.TrimSpace(k)] = strings.TrimSpace(v)
			continue
		}
		// A non-indented line ends any nested block we were reading.
		inMetadata = false
		k, v, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		key := strings.TrimSpace(k)
		val := strings.TrimSpace(v)
		if key == "metadata" && val == "" {
			// Enter the nested metadata block; its children follow indented.
			inMetadata = true
			continue
		}
		fm[key] = val
	}
	return strings.TrimLeft(rest[fenceEnd:], "\n"), fm
}

// closingFence locates the YAML frontmatter terminator: a line consisting
// solely of `---`. It returns the byte offset where that line starts (so the
// frontmatter content is s[:start]) and where it ends (so the body is
// s[end:]). Both are -1 when no such line exists.
func closingFence(s string) (start, end int) {
	offset := 0
	for _, line := range strings.SplitAfter(s, "\n") {
		if strings.TrimRight(line, "\n") == "---" {
			return offset, offset + len(line)
		}
		offset += len(line)
	}
	return -1, -1
}

// splitSections maps each `## Heading` to the raw text beneath it (up to the
// next `## ` heading). The top-level `# Title` is ignored.
func splitSections(body string) map[string]string {
	out := map[string]string{}
	var cur string
	var buf strings.Builder
	flush := func() {
		if cur != "" {
			out[cur] = strings.Trim(buf.String(), "\n")
		}
		buf.Reset()
	}
	sc := bufio.NewScanner(strings.NewReader(body))
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		if h, ok := strings.CutPrefix(line, "## "); ok {
			flush()
			cur = strings.TrimSpace(h)
			continue
		}
		if cur != "" {
			buf.WriteString(line)
			buf.WriteByte('\n')
		}
	}
	flush()
	return out
}

// bullets extracts "- " list items from a section, joining wrapped lines.
func bullets(section string) []string {
	var out []string
	for _, raw := range strings.Split(section, "\n") {
		line := strings.TrimRight(raw, " ")
		item, ok := strings.CutPrefix(line, "- ")
		if ok {
			out = append(out, strings.TrimSpace(item))
			continue
		}
		// Continuation of the previous bullet (indented wrap).
		if len(out) > 0 && strings.HasPrefix(raw, "  ") {
			out[len(out)-1] += " " + strings.TrimSpace(raw)
		}
	}
	return out
}

// parseSteps reads `### N. Title` subsections within the Procedure section into
// ordered Steps, preserving each step's markdown body (including fenced code).
func parseSteps(section string) []Step {
	var steps []Step
	var cur *Step
	var buf strings.Builder
	flush := func() {
		if cur != nil {
			cur.Body = strings.Trim(buf.String(), "\n")
			steps = append(steps, *cur)
		}
		buf.Reset()
	}
	sc := bufio.NewScanner(strings.NewReader(section))
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		if h, ok := strings.CutPrefix(line, "### "); ok {
			flush()
			title := strings.TrimSpace(h)
			// Drop a leading "N. " ordinal if present.
			if _, after, ok := strings.Cut(title, ". "); ok {
				title = after
			}
			cur = &Step{Title: title}
			continue
		}
		if cur != nil {
			buf.WriteString(line)
			buf.WriteByte('\n')
		}
	}
	flush()
	return steps
}

// TaskSkill is a single task-level skill extracted from the embedded FS.
type TaskSkill struct {
	Product     string
	TaskID      string
	Name        string
	Description string
	Version     string
	Content     string // markdown body below frontmatter
	Raw         string // complete file including frontmatter
}

// TaskSkills reads all *.md files from the embedded FS for the given product
// and returns them sorted by TaskID.
func TaskSkills(product string) ([]TaskSkill, error) {
	dir := filepath.Join("content", "tasks", product)
	entries, err := taskSkillsFS.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read task skills for %q: %w", product, err)
	}
	var skills []TaskSkill
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".md" {
			continue
		}
		data, err := taskSkillsFS.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", e.Name(), err)
		}
		ts, err := parseTaskSkill(product, e.Name(), string(data))
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", e.Name(), err)
		}
		skills = append(skills, ts)
	}
	sort.Slice(skills, func(i, j int) bool {
		return skills[i].TaskID < skills[j].TaskID
	})
	return skills, nil
}

// TaskSkillByID finds a task skill by its ID within the given product.
func TaskSkillByID(product, taskID string) (*TaskSkill, error) {
	skills, err := TaskSkills(product)
	if err != nil {
		return nil, err
	}
	for i := range skills {
		if skills[i].TaskID == taskID {
			return &skills[i], nil
		}
	}
	return nil, fmt.Errorf("task skill %q not found for product %q", taskID, product)
}

func parseTaskSkill(product, filename, src string) (TaskSkill, error) {
	taskID := strings.TrimSuffix(filename, ".md")
	body, fm := splitFrontmatter(src)
	ts := TaskSkill{
		Product: product,
		TaskID:  taskID,
		Name:    fm["name"],
		Description: fm["description"],
		Version: fm["version"],
		Content: body,
		Raw:     src,
	}
	if ts.Name == "" {
		return ts, errors.New("missing name in frontmatter")
	}
	if ts.Description == "" {
		return ts, errors.New("missing description in frontmatter")
	}
	return ts, nil
}
