"""URL-to-operation reverse lookup service."""

from __future__ import annotations

import re
import uuid
from dataclasses import dataclass
from typing import Any
from urllib.parse import parse_qs, urlparse

from jentic_one.registry.core.schema.operation_url_index import OperationURLIndex
from jentic_one.registry.core.url_index import count_segments, normalise_host, normalize_path
from jentic_one.registry.repos.url_index_repo import UrlIndexRepository
from jentic_one.registry.services.errors import (
    AmbiguousMatchError,
    MethodNotAllowedError,
    TooManyCandidatesError,
)

MAX_CANDIDATES = 500

# Safety: host_regex/path_regex values are system-generated by build_host_regex/build_path_regex
# during ingestion (not user-supplied at query time), so ReDoS risk is mitigated at the source.


@dataclass
class URLLookupResult:
    """Successful URL lookup resolution."""

    operation_id: str
    path_params: dict[str, str]
    query_params: dict[str, Any]


@dataclass
class _RankedMatch:
    operation_id: str
    revision_id: uuid.UUID
    path_params: dict[str, str]
    specificity_key: tuple[bool, int, int, int]


class URLLookupService:
    """Resolves a METHOD+URL to the matching operation in the URL index."""

    def __init__(self, session: Any) -> None:
        self._session = session

    async def resolve(
        self, *, method: str, url: str, revision_id: uuid.UUID | None = None
    ) -> URLLookupResult | None:
        """Resolve a full URL to the matching operation.

        When ``revision_id`` is None, only each API's live revision
        (``current_revision_id``) is searched — drafts, archived and superseded
        revisions never serve an unpinned lookup. Passing ``revision_id`` (a
        ``Jentic-Revision`` pin) searches exactly that revision, whatever its
        state; callers gate which revisions may be pinned.
        """
        parsed = urlparse(url)
        scheme = parsed.scheme or "https"
        raw_host = parsed.hostname or ""
        port = parsed.port
        host_str = f"{raw_host}:{port}" if port else raw_host
        host = normalise_host(host_str, scheme)
        path = normalize_path(parsed.path or "/")
        query_params = parse_qs(parsed.query)
        segment_count = count_segments(path)

        methods_to_try = [method.upper()]
        if method.upper() == "HEAD":
            methods_to_try.append("GET")

        for m in methods_to_try:
            result = await self._try_resolve(
                revision_id=revision_id,
                method=m,
                host=host,
                path=path,
                segment_count=segment_count,
            )
            if result is not None:
                return URLLookupResult(
                    operation_id=result.operation_id,
                    path_params=result.path_params,
                    query_params=query_params,
                )

        if revision_id is not None:
            await self._check_method_not_allowed(
                revision_id=revision_id,
                host=host,
                path=path,
                segment_count=segment_count,
            )

        return None

    async def _try_resolve(
        self,
        *,
        revision_id: uuid.UUID | None,
        method: str,
        host: str,
        path: str,
        segment_count: int,
    ) -> _RankedMatch | None:
        if revision_id is not None:
            candidates = await UrlIndexRepository.lookup_by_host(
                self._session,
                revision_id=revision_id,
                method=method,
                host=host,
                segment_count=segment_count,
            )
            if not candidates:
                regex_candidates = await UrlIndexRepository.lookup_by_host_regex(
                    self._session,
                    revision_id=revision_id,
                    method=method,
                    segment_count=segment_count,
                )
                candidates = [
                    c
                    for c in regex_candidates
                    if c.host_regex and re.fullmatch(c.host_regex, host, re.IGNORECASE)
                ]
        else:
            candidates = await UrlIndexRepository.lookup_by_host_live(
                self._session,
                method=method,
                host=host,
                segment_count=segment_count,
            )
            if not candidates:
                regex_candidates = await UrlIndexRepository.lookup_by_host_regex_live(
                    self._session,
                    method=method,
                    segment_count=segment_count,
                )
                candidates = [
                    c
                    for c in regex_candidates
                    if c.host_regex and re.fullmatch(c.host_regex, host, re.IGNORECASE)
                ]

        if not candidates:
            return None

        if len(candidates) > MAX_CANDIDATES:
            raise TooManyCandidatesError()

        return self._match_and_rank(candidates, path)

    async def _check_method_not_allowed(
        self,
        *,
        revision_id: uuid.UUID,
        host: str,
        path: str,
        segment_count: int,
    ) -> None:
        """Check if the URL matches other methods — if so, raise MethodNotAllowedError."""
        any_method = await UrlIndexRepository.lookup_by_host_any_method(
            self._session,
            revision_id=revision_id,
            host=host,
            segment_count=segment_count,
        )
        if not any_method:
            any_method = await UrlIndexRepository.lookup_by_host_regex_any_method(
                self._session,
                revision_id=revision_id,
                segment_count=segment_count,
            )
            any_method = [
                c
                for c in any_method
                if c.host_regex and re.fullmatch(c.host_regex, host, re.IGNORECASE)
            ]

        if not any_method:
            return

        matching_methods: set[str] = set()
        for candidate in any_method:
            match = re.fullmatch(candidate.path_regex, path)
            if match:
                matching_methods.add(candidate.method)

        if matching_methods:
            raise MethodNotAllowedError(sorted(matching_methods))

    @staticmethod
    def _match_and_rank(candidates: list[OperationURLIndex], path: str) -> _RankedMatch | None:
        matches: list[_RankedMatch] = []
        for candidate in candidates:
            match = re.fullmatch(candidate.path_regex, path)
            if not match:
                continue
            path_params = match.groupdict()
            is_parameterized = bool(candidate.param_names)
            template_parts = candidate.path_template.strip("/").split("/")
            literal_count = sum(1 for p in template_parts if not p.startswith("{"))
            first_literal_pos = next(
                (i for i, p in enumerate(template_parts) if not p.startswith("{")),
                len(template_parts),
            )
            last_literal_pos = next(
                (i for i, p in reversed(list(enumerate(template_parts))) if not p.startswith("{")),
                -1,
            )
            specificity_key = (
                is_parameterized,
                -literal_count,
                first_literal_pos,
                -last_literal_pos,
            )
            matches.append(
                _RankedMatch(
                    operation_id=candidate.operation_id,
                    revision_id=candidate.revision_id,
                    path_params=path_params,
                    specificity_key=specificity_key,
                )
            )

        if not matches:
            return None

        # ``sort`` is stable, so equally specific matches keep the candidate order.
        # Unpinned candidates arrive most-recently-live revision first (see
        # ``UrlIndexRepository.lookup_by_host_live``): when two live revisions
        # (e.g. two versions of one vendor's API) serve the same URL, the newest
        # wins, as it did before the index was scoped per revision. Ambiguity is
        # only an error *within* the winning revision — its own spec is at fault.
        matches.sort(key=lambda m: m.specificity_key)
        best = matches[0]
        tied = [
            m
            for m in matches
            if m.specificity_key == best.specificity_key and m.revision_id == best.revision_id
        ]
        if len(tied) > 1:
            raise AmbiguousMatchError(len(tied))

        return best
