// Package client is the public, importable Go SDK for the Jentic platform.
//
// It exposes typed HTTP clients, authentication, and config/context resolution
// so third-party Go programs can talk to the Jentic control and broker planes
// WITHOUT shelling out to the jentic binary. The jentic CLI and the jenticctl
// installer are themselves thin consumers of this same surface.
//
// Import as github.com/jentic/jentic-one/cli/client/... — the same module as the
// CLI, no separate go.mod (impl/7.0 §2).
//
// # Public surface
//
//   - client                              — top-level constructors + Config: NewControl, NewControlRaw, NewBroker, RawControlRequest, ProbeServerVersion, BrokerTransport.
//   - client/generated/{control,broker}   — typed OpenAPI clients + spec companions (read-only, generated by `make generate-api`): ClientWithResponses, request/response models, RequiredFields(), SensitiveFields, the op index.
//   - client/auth                          — keys, token state (XDG state dir), RFC 7523 OAuth, request editor: Credentials, RequestEditor, GetOrGenerateKey, TokenSet, ReadTokens/SaveTokens, API-key storage.
//   - client/config                        — XDG paths, config.yaml load/mutate, env-var (file-less) resolution: Config, ResolvedState, LoadState, Load, MutateConfig, ConfigDir, CacheDir, StateDir.
//   - client/paginate                      — generic cursor-walk over the list-endpoint convention: Page, PageFn, All, ForEach.
//
// See the runnable examples in this package (example_test.go) for the two
// authentication modes (injected bearer vs. disk-backed identity), reusing the
// CLI's own state resolution, and draining a paginated endpoint.
//
// # The clean boundary
//
// The whole SDK is driven by one UX-free struct, client.Config. There is
// deliberately NO Mode or Theme here: formatting, prompting, redaction, and
// mode-fencing are CLI concerns and are intentionally absent from the SDK. The
// dependency arrow is one-directional — internal/ -> client/, never the reverse —
// and the public command-tree composition layer (pkg/core, pkg/clitree) depends
// on client/, never the reverse. Arch test Test1A_SDKBoundary
// (cli/tests/arch/boundary_test.go) enforces that client/... imports nothing from
// internal/..., pkg/..., cobra, or the ux/theme UX layers.
//
// # What is intentionally NOT here
//
// The following stay CLI-private under internal/ and are never part of the SDK
// contract (impl/7.0 §2): the Cobra command implementations, the ux
// audience/mode layer and theme, the local-agent isolation layer (account
// lifecycle, confinement, ACL grants — host-side OS tooling, not API surface),
// and the jenticctl installer/lifecycle packages. Downstream binaries that want
// to embed and extend the Cobra command tree use the public pkg/ composition
// packages instead.
//
// # Stability & versioning
//
// Because the SDK is public, anything exported is an API contract:
//
//   - Generated clients track the specs. client/generated/* is regenerated from
//     the upstream OpenAPI specs; a breaking spec change is a breaking change for
//     importers. Treat spec bumps as deliberate, semver-significant events — never
//     regenerate silently in a patch release.
//   - Semantic import versioning. The module is v0 during the product beta (the
//     cli/vX.Y.Z tag mirrors the 0.x app release), so Go makes no stability promise
//     yet — breaking Go API changes are permitted in minors but MUST be flagged in
//     the release notes. Once the SDK is declared stable (v1), breaking changes to
//     Config, the constructors, client/auth, or client/config require a major bump
//     (and, per Go rules, a /v2+ module path suffix).
//   - ResolvedState.Persisted* fields are SDK-internal-by-convention: they exist so
//     the CLI can interpret mode/theme. SDK consumers should not depend on them for
//     behavior; they may change without a major bump.
//   - Generated code is read-only. Never hand-edit client/generated/*; customize
//     via a RequestEditor or a custom *http.Client instead.
//
// # Tradeoffs
//
// Same-module distribution means importing client transitively pulls the repo's
// full dependency graph (Cobra etc. are in go.mod even if you only use client).
// This is an accepted decision; the package boundary here makes splitting client/
// into its own module a mechanical move later if the dependency weight matters.
// The SDK gives typed clients and auth only — it makes no UX guarantees.
package client
