package install

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

// Docker compose service names and container-side paths. render.go emits config
// values relative to these so the mounted config matches the running container.
const (
	composeServiceDB     = "db"
	composeServiceApp    = "app"
	composeServiceBroker = "broker"

	// containerConfigPath is where the generated jentic-one.yaml is mounted.
	containerConfigPath = "/etc/jentic/jentic-one.yaml"
	// containerDataDir is the bind-mounted directory holding SQLite *.db files.
	containerDataDir = "/data"
	// containerLogsDir is the bind-mounted directory for the JSON log sink.
	containerLogsDir = "/logs"

	// AppImageTag is the fixed local tag the CLI builds the combined app image
	// with and the generated compose file references.
	AppImageTag = "jentic-one/app:jentic-cli"

	// postgresImage is the managed Postgres image (matches docker/local-setup).
	postgresImage = "postgres:16"

	// composeDataVolume is the named volume that backs the SQLite databases.
	// SQLite must NOT live on a host bind mount: Docker Desktop's virtiofs /
	// gRPC-FUSE file sharing does not support the locking/fsync semantics SQLite
	// needs, which surfaces as "disk I/O error". A named volume lives on the
	// Linux VM's native filesystem where SQLite works correctly.
	composeDataVolume = "jentic-data"

	// postgresDataVolume is the named volume that backs the managed Postgres
	// data dir (the Postgres install path uses this instead of jentic-data).
	postgresDataVolume = "db-data"

	// composeProjectName pins the docker compose project name so it does not
	// vary with the install directory (JENTIC_HOME). Without an explicit name,
	// Compose derives the project from the compose file's directory basename and
	// normalizes it, which makes the resulting volume names (project-prefixed)
	// unpredictable — and breaks any out-of-band `docker volume rm` recovery.
	// Pinning it makes both `down -v` and the uninstall hint deterministic.
	composeProjectName = "jentic"

	// initSchemasName is the bootstrap SQL written beside the compose file and
	// mounted into the Postgres container's init directory.
	initSchemasName = "init-schemas.sql"
)

// DataVolumeNames returns the fully-qualified (project-prefixed) docker volume
// names that back the database for the given install mode, exactly as Compose
// creates them given the pinned project name. They are exposed so the uninstall
// path can point operators at the precise volume(s) to remove by hand if
// `docker compose down -v` could not run (e.g. the daemon was down). postgres
// reports the managed-Postgres volume; otherwise the SQLite data volume.
func DataVolumeNames(postgres bool) []string {
	vol := composeDataVolume
	if postgres {
		vol = postgresDataVolume
	}
	return []string{composeProjectName + "_" + vol}
}

// AllDataVolumeNames returns the project-prefixed data volume names for BOTH
// install modes (SQLite and Postgres). The uninstall recovery hint uses it when
// the install mode is unknown (no manifest), so the operator is shown every
// candidate volume to remove by hand rather than being pointed at one guess.
func AllDataVolumeNames() []string {
	return []string{
		composeProjectName + "_" + composeDataVolume,
		composeProjectName + "_" + postgresDataVolume,
	}
}

// initSchemasSQL bootstraps the schemas the app expects on the managed
// Postgres. It runs once on first container boot. The app connects as the
// configured superuser, so per-surface roles are not required.
const initSchemasSQL = `-- Generated by 'jenticctl install'. Bootstraps the managed Postgres for jentic-one.
CREATE SCHEMA IF NOT EXISTS registry;
CREATE SCHEMA IF NOT EXISTS control;
CREATE SCHEMA IF NOT EXISTS admin;
`

// ComposeConfig carries the host-side paths the generated compose stack binds
// into the containers. All paths should be absolute.
type ComposeConfig struct {
	// ComposePath is where the generated docker-compose.yaml is written.
	ComposePath string
	// ConfigHostPath is the generated jentic-one.yaml mounted read-only at
	// containerConfigPath.
	ConfigHostPath string
	// LogsHostDir is bind-mounted at containerLogsDir for the file log sink.
	LogsHostDir string
}

// InitSchemasPath returns the path of the Postgres bootstrap SQL written beside
// the compose file.
func (c ComposeConfig) InitSchemasPath() string {
	return filepath.Join(filepath.Dir(c.ComposePath), initSchemasName)
}

// composeParams is the data passed to the compose template.
type composeParams struct {
	Postgres            bool
	ProjectName         string
	AppImage            string
	Apps                string
	ConfigHostPath      string
	ContainerConfigPath string
	LogsHostDir         string
	ContainerLogsDir    string
	DataVolume          string
	ContainerDataDir    string
	ServerPort          string
	BrokerPort          string
	PostgresImage       string
	PGName              string
	PGUser              string
	PGPassword          string
	PGPublishedPort     string
	InitSchemasPath     string
	DBService           string
	BrokerService       string
}

const composeTemplate = `# Generated by 'jenticctl install'. Brings up the jentic-one app{{if .Postgres}} and a
# managed Postgres{{end}} via docker compose. Regenerate it with 'jenticctl install';
# manual edits are overwritten on the next install.
name: {{.ProjectName}}
services:
{{- if .Postgres}}
  {{.DBService}}:
    image: {{.PostgresImage}}
    environment:
      POSTGRES_DB: {{.PGName}}
      POSTGRES_USER: {{.PGUser}}
      POSTGRES_PASSWORD: {{.PGPassword}}
    ports:
      - "{{.PGPublishedPort}}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - {{.InitSchemasPath}}:/docker-entrypoint-initdb.d/init-schemas.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{.PGUser}} -d {{.PGName}}"]
      interval: 5s
      timeout: 3s
      retries: 5
{{- end}}
  app:
    image: {{.AppImage}}
    environment:
      JENTIC_CONFIG_FILE: {{.ContainerConfigPath}}
      JENTIC__APPS: {{.Apps}}
      # The image runs as uid 999 (jentic) whose $HOME (/home/jentic) is not
      # writable, so point the HuggingFace / sentence-transformers model cache at
      # the writable /tmp. Without this the registry ingest pipeline's embedding
      # stage dies with "[Errno 13] Permission denied: '/home/jentic'".
      HF_HOME: /tmp/hf-cache
      SENTENCE_TRANSFORMERS_HOME: /tmp/hf-cache
    ports:
      - "{{.ServerPort}}:{{.ServerPort}}"
    volumes:
      - {{.ConfigHostPath}}:{{.ContainerConfigPath}}:ro
      - {{.LogsHostDir}}:{{.ContainerLogsDir}}
{{- if not .Postgres}}
      - {{.DataVolume}}:{{.ContainerDataDir}}
{{- end}}
{{- if .Postgres}}
    depends_on:
      {{.DBService}}:
        condition: service_healthy
{{- end}}
  {{.BrokerService}}:
    image: {{.AppImage}}
    environment:
      JENTIC_CONFIG_FILE: {{.ContainerConfigPath}}
      # The broker cannot be bundled with other surfaces, so it runs as its own
      # service with apps=broker on a dedicated port.
      JENTIC__APPS: broker
      JENTIC__SERVER__PORT: "{{.BrokerPort}}"
      # Same writable model-cache redirect as the app service (uid 999's $HOME
      # is not writable); harmless for the broker, required if it touches the
      # embedding code paths.
      HF_HOME: /tmp/hf-cache
      SENTENCE_TRANSFORMERS_HOME: /tmp/hf-cache
    ports:
      - "{{.BrokerPort}}:{{.BrokerPort}}"
    volumes:
      - {{.ConfigHostPath}}:{{.ContainerConfigPath}}:ro
      - {{.LogsHostDir}}:{{.ContainerLogsDir}}
{{- if not .Postgres}}
      - {{.DataVolume}}:{{.ContainerDataDir}}
{{- end}}
{{- if .Postgres}}
    depends_on:
      {{.DBService}}:
        condition: service_healthy
{{- end}}

volumes:
{{- if .Postgres}}
  db-data:
{{- else}}
  {{.DataVolume}}:
{{- end}}
`

var composeTmpl = template.Must(template.New("compose").Parse(composeTemplate))

// RenderCompose returns the docker-compose.yaml bytes for the draft, wiring the
// host paths in cfg into the app (and managed Postgres) containers.
func RenderCompose(d *Draft, cfg ComposeConfig) ([]byte, error) {
	params := composeParams{
		Postgres:            d.IsPostgres(),
		ProjectName:         composeProjectName,
		AppImage:            AppImageTag,
		Apps:                strings.Join(d.Apps, ","),
		ConfigHostPath:      cfg.ConfigHostPath,
		ContainerConfigPath: containerConfigPath,
		LogsHostDir:         cfg.LogsHostDir,
		ContainerLogsDir:    containerLogsDir,
		DataVolume:          composeDataVolume,
		ContainerDataDir:    containerDataDir,
		ServerPort:          d.ServerPort,
		BrokerPort:          d.BrokerPort,
		PostgresImage:       postgresImage,
		PGName:              d.PGName,
		PGUser:              d.PGUser,
		PGPassword:          d.PGPassword,
		PGPublishedPort:     d.PGPort,
		InitSchemasPath:     cfg.InitSchemasPath(),
		DBService:           composeServiceDB,
		BrokerService:       composeServiceBroker,
	}
	var buf bytes.Buffer
	if err := composeTmpl.Execute(&buf, params); err != nil {
		return nil, fmt.Errorf("render compose: %w", err)
	}
	return buf.Bytes(), nil
}

// WriteComposeArtifacts renders and writes the compose file (and, for Postgres,
// the bootstrap init SQL) and ensures the bind-mount directories exist.
func WriteComposeArtifacts(d *Draft, cfg ComposeConfig) error {
	data, err := RenderCompose(d, cfg)
	if err != nil {
		return err
	}
	if err := os.WriteFile(cfg.ComposePath, data, 0o600); err != nil {
		return fmt.Errorf("write %s: %w", cfg.ComposePath, err)
	}
	// Postgres bootstraps schemas via an init script; SQLite lives in a named
	// volume (no host data dir to create — see composeDataVolume).
	if d.IsPostgres() {
		if err := os.WriteFile(cfg.InitSchemasPath(), []byte(initSchemasSQL), 0o600); err != nil {
			return fmt.Errorf("write %s: %w", cfg.InitSchemasPath(), err)
		}
	}
	if err := os.MkdirAll(cfg.LogsHostDir, 0o700); err != nil {
		return fmt.Errorf("create logs dir: %w", err)
	}
	return nil
}

// BuildImages builds the shared python-base (builder + runtime) stages and the
// combined app image tagged AppImageTag, from the plan's source checkout
// (cloning first when FromGit). Output streams to w. The python-base targets
// must be built first since app.Dockerfile starts FROM python-base:runtime and
// copies the wheel from python-base:builder.
func (p BuildPlan) BuildImages(w io.Writer) error {
	if _, err := exec.LookPath("docker"); err != nil {
		return errors.New("`docker` is required to build the images but was not found on " +
			"PATH (install it: https://docs.docker.com/get-docker/)")
	}
	if p.FromGit {
		if _, err := exec.LookPath("git"); err != nil {
			return errors.New("`git` is required to download the source but was not found on PATH")
		}
		if err := p.fetchSource(w); err != nil {
			return err
		}
	}

	steps := [][]string{
		{"build", "-f", "deploy/docker/python-base.Dockerfile", "--target", "builder", "-t", "python-base:builder", "."},
		{"build", "-f", "deploy/docker/python-base.Dockerfile", "--target", "runtime", "-t", "python-base:runtime", "."},
		{"build", "-f", "deploy/docker/app.Dockerfile", "-t", AppImageTag, "."},
	}
	for _, args := range steps {
		if err := p.buildOne(w, args); err != nil {
			return err
		}
	}
	return nil
}

// buildKitCrashSignatures are substrings of the transient BuildKit/Docker
// Desktop transport faults that are NOT a jentic bug: a wedged builder,
// resource starvation, or client/server skew. They abort the build with a raw
// error but usually succeed on a retry after the builder is recreated (#653).
// Kept deliberately narrow — daemon/transport crashes, not ordinary "failed to
// solve" build errors (a real Dockerfile/code error would just fail again and
// mask the true cause).
var buildKitCrashSignatures = []string{
	"frontend grpc server closed unexpectedly",
	"error reading from server: eof",
	"the docker daemon is not running",
	"cannot connect to the docker daemon",
	"buildkit: connection reset by peer",
}

// recoveryBuilderName is the dedicated buildx builder the crash-recovery path
// creates so it never removes or clobbers the operator's default/active builder.
const recoveryBuilderName = "jentic-recovery"

// looksLikeBuildKitCrash reports whether build output carries a transient
// BuildKit-fault signature worth a builder-reset retry.
func looksLikeBuildKitCrash(output string) bool {
	lower := strings.ToLower(output)
	for _, sig := range buildKitCrashSignatures {
		if strings.Contains(lower, strings.ToLower(sig)) {
			return true
		}
	}
	return false
}

// buildOne runs a single `docker build` step, recovering once from a transient
// BuildKit crash by recreating the buildx builder and retrying. On a persistent
// failure it returns an actionable error with the operator workaround rather
// than the raw grpc/solve error (#653).
//
// Recovery recreates the builder (`docker buildx rm` + `create --use`) rather
// than falling back to the legacy builder (DOCKER_BUILDKIT=0): the project's
// Dockerfiles declare `# syntax=docker/dockerfile:1`, which the classic builder
// ignores today but is moving to hard-reject — so a legacy fallback would be
// dead-on-arrival and mask the transient nature of the original crash. A fresh
// builder is the actual remedy for a wedged BuildKit and keeps us on the
// supported path.
func (p BuildPlan) buildOne(w io.Writer, args []string) error {
	out, err := runCapture(w, p.SourceDir, args...)
	if err == nil {
		return nil
	}
	if !looksLikeBuildKitCrash(out) {
		return fmt.Errorf("docker %s: %w", strings.Join(args, " "), err)
	}
	fmt.Fprint(w, "\n"+warnStyle.Render(
		"BuildKit crashed (a Docker Desktop fault, not a jentic bug); "+
			"recreating the build builder and retrying once...")+"\n")
	retryArgs := args
	if p.resetBuildxBuilder(w) {
		retryArgs = buildxArgsForBuilder(args, recoveryBuilderName)
	}
	if _, err2 := runCapture(w, p.SourceDir, retryArgs...); err2 != nil {
		return fmt.Errorf("docker %s failed even after recreating the builder — "+
			"this is a Docker/BuildKit fault, not a jentic bug. Recover by: "+
			"(1) restart Docker Desktop (or your daemon); "+
			"(2) reset the builder: `docker buildx rm %s` then `docker buildx create --use`; "+
			"(3) re-run `jenticctl install`. "+
			"Underlying error: %w", strings.Join(args, " "), recoveryBuilderName, err2)
	}
	return nil
}

// resetBuildxBuilder best-effort recreates a dedicated buildx builder so the
// retry can run on a fresh BuildKit instance rather than the wedged one, and
// reports whether that builder is now available to target. It deliberately does
// NOT pass `--use`: switching the operator's active builder is a persistent,
// unrelated side effect we must not leave behind. The retry instead targets the
// recovery builder explicitly via `--builder` (see buildxArgsForBuilder). If
// buildx is unavailable it returns false and the retry falls back to whatever
// builder docker selects, with the persistent-failure error still guiding the
// operator.
func (p BuildPlan) resetBuildxBuilder(w io.Writer) bool {
	if _, err := exec.LookPath("docker"); err != nil {
		return false
	}
	// Remove any prior recovery builder (ignore "not found"), then create a
	// fresh one. Output is captured (not streamed) to keep the recovery quiet.
	_, _ = runCapture(w, p.SourceDir, "buildx", "rm", recoveryBuilderName)
	if _, err := runCapture(w, p.SourceDir, "buildx", "create", "--name", recoveryBuilderName); err != nil {
		return false
	}
	return true
}

// buildxArgsForBuilder rewrites a plain `docker build …` invocation to run on a
// named buildx builder without disturbing the operator's default —
// `docker buildx build --builder <name> --load …`. A non-`build` invocation is
// returned unchanged (best-effort), so the retry still happens on the default
// builder.
//
// --load is essential: the recovery builder uses the default `docker-container`
// driver, which keeps build results in the buildx cache rather than the local
// image store. Without --load the `-t` tag would not appear in `docker images`,
// so the next build step (`FROM python-base:…`) or `compose up` would fail with
// a missing image even though the recovery "succeeded".
func buildxArgsForBuilder(args []string, builder string) []string {
	if len(args) == 0 || args[0] != "build" {
		return args
	}
	return append([]string{"buildx", "build", "--builder", builder, "--load"}, args[1:]...)
}

// RenderDockerBuildHeader returns a styled description of the image build.
func (p BuildPlan) RenderDockerBuildHeader() string {
	var b strings.Builder
	b.WriteString(headingStyle.Render("Build (Docker images)"))
	b.WriteString("\n")
	p.writeSourceLine(&b)
	b.WriteString("  image:  " + commandStyle.Render(AppImageTag) + "\n")
	return b.String()
}

// composeArgs prefixes a compose subcommand with the project name and file
// selector so every invocation targets the generated stack deterministically,
// regardless of cwd or whether the file's pinned `name:` was hand-edited. The
// explicit `-p` makes `down -v` and the volume names predictable even if the
// compose file is altered out from under us.
func composeArgs(composePath string, sub ...string) []string {
	return append([]string{"compose", "-p", composeProjectName, "-f", composePath}, sub...)
}

// ComposeUp brings the stack up in detached mode.
func ComposeUp(w io.Writer, composePath string) error {
	return run(w, "docker", composeArgs(composePath, "up", "-d")...)
}

// ComposeDown stops and removes the stack's containers (volumes are preserved).
func ComposeDown(w io.Writer, composePath string) error {
	return run(w, "docker", composeArgs(composePath, "down")...)
}

// ComposeDownVolumes stops and removes the stack's containers AND its named
// volumes (`down -v`). This discards the database: SQLite's data volume or the
// managed Postgres data dir. Use it to recover from an incompatible Postgres
// image upgrade (a newer major refuses a data dir initialized by an older one),
// which surfaces as the container failing to start. The data is unrecoverable
// afterwards, so callers must confirm first. If `docker` is not on PATH it
// returns an error immediately rather than failing deep in exec, so callers
// (uninstall) can surface the manual-removal hint instead of hanging.
func ComposeDownVolumes(w io.Writer, composePath string) error {
	if _, err := exec.LookPath("docker"); err != nil {
		return errors.New("`docker` not found on PATH; cannot tear down the stack volumes")
	}
	return run(w, "docker", composeArgs(composePath, "down", "-v")...)
}

// RemoveDataVolumes removes the named docker volumes explicitly, by name. It is
// the belt-and-suspenders companion to ComposeDownVolumes: `docker compose down
// -v` only removes volumes declared in the compose file for the pinned project,
// so a volume created under a different project name (a pre-pinning install, a
// regenerated compose file, or a stack first brought up from a different
// directory basename) survives an otherwise-successful `down -v`. Removing the
// project-prefixed volume names directly closes that gap.
//
// A volume that does not exist is treated as a no-op (not an error): the goal is
// "ensure gone", and `down -v` having already removed it is success, not
// failure. It returns the names that were actually removed so the caller can
// report accurately. If docker is not on PATH it returns an error immediately so
// the caller can surface the manual-removal hint rather than failing deep in
// exec.
func RemoveDataVolumes(w io.Writer, names []string) (removed []string, err error) {
	if _, err := exec.LookPath("docker"); err != nil {
		return nil, errors.New("`docker` not found on PATH; cannot remove the data volume(s)")
	}
	for _, name := range names {
		out, rmErr := runCapture(w, "", "volume", "rm", name)
		if rmErr == nil {
			removed = append(removed, name)
			continue
		}
		// `docker volume rm` on a missing volume exits non-zero with "no such
		// volume" — that is the success case for us (it is already gone). Any
		// other failure (e.g. the volume is still in use) is a real error.
		if strings.Contains(strings.ToLower(out), "no such volume") {
			continue
		}
		return removed, fmt.Errorf("docker volume rm %s: %w", name, rmErr)
	}
	return removed, nil
}

// ComposePs returns the `docker compose ps` output for the stack.
func ComposePs(composePath string) (string, error) {
	out, err := exec.Command("docker", composeArgs(composePath, "ps")...).CombinedOutput() //nolint:gosec // composePath is CLI-managed under JENTIC_HOME.
	return string(out), err
}

// RunComposeMigrations applies migrations via a one-shot app container
// (`docker compose run --rm app python -m jentic_one.migrations.run`). For
// Postgres, compose waits on the db healthcheck via the app's depends_on.
func RunComposeMigrations(w io.Writer, composePath string) error {
	return run(w, "docker", migrateArgs(composePath)...)
}

// SchemaState is the migration state of the stack's databases.
type SchemaState int

const (
	// SchemaUnknown means the state could not be determined — the check could
	// not run at all (no docker, an app image predating `--check`, an
	// unreachable database). Callers must treat it as "carry on": refusing to
	// start because a *diagnostic* failed would be a worse regression than the
	// bug the check exists to catch.
	SchemaUnknown SchemaState = iota
	// SchemaCurrent means every database is at head.
	SchemaCurrent
	// SchemaUninitialized means at least one database has no schema at all
	// (no Alembic version table). A wiped or brand-new volume. There is no data
	// to protect, so creating the schema is safe and needs no confirmation.
	SchemaUninitialized
	// SchemaPending means at least one database has a schema but is behind
	// head. It holds data that forward-only migrations will rewrite, so this is
	// the operator's call to make with a backup in hand — never automatic.
	SchemaPending
)

// checkExitNeedsMigration is the exit code `migrations.run --check` uses for
// "not at head". Kept distinct from 1 so a genuine failure of the check (bad
// config, database unreachable) is not misread as a schema verdict.
const checkExitNeedsMigration = 3

// ComposeSchemaState reports whether the stack's databases are migrated, without
// modifying them. It runs `migrations.run --check` in a one-shot app container.
//
// Any failure to *obtain* an answer yields SchemaUnknown with a nil error: the
// caller cannot act on a non-answer, and blocking a start on a broken
// diagnostic would be worse than the problem being diagnosed. Only the schema
// verdict itself is authoritative.
func ComposeSchemaState(composePath string) (SchemaState, error) {
	if _, err := exec.LookPath("docker"); err != nil {
		return SchemaUnknown, nil
	}
	//nolint:gosec // composePath is CLI-managed under JENTIC_HOME.
	out, err := exec.Command("docker", migrateCheckArgs(composePath)...).CombinedOutput()
	text := string(out)

	// Parse the verdict first: it is the authoritative signal, and `--check`
	// exits non-zero *by design* when migrations are needed.
	if state, ok := parseSchemaVerdict(text); ok {
		return state, nil
	}
	if err != nil {
		// No verdict and a failure: an old image without `--check` (argparse
		// exits 2), no docker daemon, an unreachable database. Undeterminable.
		return SchemaUnknown, nil
	}
	return SchemaUnknown, nil
}

// parseSchemaVerdict extracts the OVERALL line that `migrations.run --check`
// prints last. Reported as a verdict only when explicitly found, so garbled or
// truncated output degrades to "unknown" rather than to a wrong answer.
func parseSchemaVerdict(out string) (SchemaState, bool) {
	for _, line := range strings.Split(out, "\n") {
		fields := strings.Fields(strings.TrimSpace(line))
		if len(fields) != 2 || fields[0] != "OVERALL" {
			continue
		}
		switch fields[1] {
		case "current":
			return SchemaCurrent, true
		case "uninitialized":
			return SchemaUninitialized, true
		case "pending":
			return SchemaPending, true
		}
	}
	return SchemaUnknown, false
}

// migrateCheckArgs builds the read-only schema probe. It reuses migrateArgs so
// the check always runs the same entrypoint, in the same one-shot container, as
// the migration it gates.
func migrateCheckArgs(composePath string) []string {
	return append(migrateArgs(composePath), "--check")
}

// migrateArgs builds the `docker compose run` invocation that applies
// migrations via a one-shot app container. -T disables pseudo-TTY allocation:
// the run is non-interactive and CLI-driven, so without it `docker compose run`
// fails with "the input device is not a TTY" when stdin is not a terminal.
func migrateArgs(composePath string) []string {
	return composeArgs(composePath, "run", "--rm", "-T", composeServiceApp,
		"python", "-m", "jentic_one.migrations.run")
}

// ComposeCreateAdmin runs the one-time first-run admin creation inside a
// one-shot app container (`docker compose run --rm -T app python -m jentic_one
// create-admin`). The password is passed on the child's stdin (never argv) so
// it does not leak into the process table or shell history. -T keeps the run
// non-interactive; the Python side reads the password from stdin when not a TTY.
func ComposeCreateAdmin(w io.Writer, composePath, email, password string) error {
	args := composeArgs(composePath, "run", "--rm", "-T", composeServiceApp,
		"python", "-m", "jentic_one", "create-admin", "--email", email)
	cmd := exec.Command("docker", args...) //nolint:gosec // composePath/email are CLI-managed; password is piped via stdin.
	cmd.Stdin = strings.NewReader(password + "\n")
	cmd.Stdout = w
	cmd.Stderr = w
	return cmd.Run()
}

// VenvCreateAdmin runs first-run admin creation against a local (non-Docker)
// install by invoking the venv Python directly. The password is piped on stdin
// for the same reasons as ComposeCreateAdmin.
func VenvCreateAdmin(w io.Writer, venvPython, configPath, email, password string) error {
	cmd := exec.Command(venvPython, "-m", "jentic_one", "create-admin", "--email", email) //nolint:gosec // venvPython/configPath are CLI-managed under JENTIC_HOME; password is piped via stdin.
	cmd.Env = append(os.Environ(), "JENTIC_CONFIG_FILE="+configPath)
	cmd.Stdin = strings.NewReader(password + "\n")
	cmd.Stdout = w
	cmd.Stderr = w
	return cmd.Run()
}

// ComposeResetPassword sets a temporary password for an existing user inside a
// one-shot app container, forcing a change at next sign-in. The temporary
// password is piped on the child's stdin (never argv) for the same reasons as
// ComposeCreateAdmin.
func ComposeResetPassword(w io.Writer, composePath, email, password string) error {
	args := composeArgs(composePath, "run", "--rm", "-T", composeServiceApp,
		"python", "-m", "jentic_one", "reset-password", "--email", email)
	cmd := exec.Command("docker", args...) //nolint:gosec // composePath/email are CLI-managed; password is piped via stdin.
	cmd.Stdin = strings.NewReader(password + "\n")
	cmd.Stdout = w
	cmd.Stderr = w
	return cmd.Run()
}

// VenvResetPassword sets a temporary password for an existing user against a
// local (non-Docker) install by invoking the venv Python directly. The password
// is piped on stdin for the same reasons as ComposeResetPassword.
func VenvResetPassword(w io.Writer, venvPython, configPath, email, password string) error {
	cmd := exec.Command(venvPython, "-m", "jentic_one", "reset-password", "--email", email) //nolint:gosec // venvPython/configPath are CLI-managed under JENTIC_HOME; password is piped via stdin.
	cmd.Env = append(os.Environ(), "JENTIC_CONFIG_FILE="+configPath)
	cmd.Stdin = strings.NewReader(password + "\n")
	cmd.Stdout = w
	cmd.Stderr = w
	return cmd.Run()
}
