// Package install powers the `jenticctl install` onboarding wizard: an interactive
// form (Charm huh + lipgloss) that collects deployment + configuration choices,
// generates a jentic-one.yaml mirroring the app's AppConfig, then builds the
// stack, applies migrations, and starts the app.
//
// The wizard is a hub-and-spoke TUI (see wizard.go): a deployment page, then a
// menu of configuration sections (see sections.go) each drilling into a small
// form. Onboarding a new AppConfig option means: add a field to Draft, add it to
// a Section's fields/summary, and map it in render.go.
package install

// Runtime paths the user can install onto.
const (
	RuntimeSource = "source" // run from source (uv) on the host
	RuntimeDocker = "docker" // containerized via docker compose
)

// Database backends (mirrors DatabaseConfig.backend in shared/config.py).
const (
	BackendSQLite   = "sqlite"
	BackendPostgres = "postgres"
)

// DefaultBrokerPort is the default port the broker service binds to. It must
// differ from the app's server port (default 8000) since the broker runs as
// its own process/container.
const DefaultBrokerPort = "8100"

// AllSurfaces are the surfaces selectable for the combined `apps` list. The
// broker is deliberately excluded: it cannot be bundled with other surfaces
// (the backend's __main__._build_app rejects `apps` containing "broker"
// alongside anything else), so the installer always runs it as its own
// service on its own port instead. See Draft.BrokerPort.
var AllSurfaces = []string{"registry", "admin", "control", "auth"}

// Draft holds every answer collected by the wizard. Fields are bound directly to
// huh form fields (hence the string-typed ports), then translated into the
// on-disk config by render.go.
type Draft struct {
	// RuntimePath selects how the stack runs: from source or in containers.
	RuntimePath string

	// DBBackend selects the database backend for every surface.
	DBBackend string

	// Postgres connection (used when DBBackend == BackendPostgres). All surfaces
	// share one server; they are isolated by schema_name.
	PGHost     string
	PGPort     string
	PGName     string
	PGUser     string
	PGPassword string

	// SQLiteDir is the directory holding per-surface *.db files (BackendSQLite).
	SQLiteDir string

	// Apps is the set of enabled surfaces (maps to AppConfig.apps).
	Apps []string

	// Server binding (maps to AppConfig.server).
	ServerHost string
	ServerPort string

	// BrokerPort is the host/bind port for the broker service. The broker runs
	// as its own process (source) or container (Docker) with apps=[broker],
	// since it cannot share the combined app. It must differ from ServerPort.
	BrokerPort string

	// Runtime knobs (maps to AppConfig.runtime).
	Debug    bool
	LogLevel string

	// File logging sink (maps to AppConfig.logging). When LogFileEnabled the app
	// mirrors its logs as one JSON object per line to LogFileDir/LogFileName, in
	// addition to stdout (which the CLI captures separately). LogFileDir is set
	// to the absolute ~/.jentic/logs by the install command before rendering.
	LogFileEnabled bool
	LogFileDir     string
	LogFileName    string

	// Observability exporters (maps to AppConfig.observability).
	MetricsExporter string
	TracingExporter string

	// Auth (maps to AppConfig.auth). AuthBaseURL overrides canonical_base_url;
	// when empty it is derived from the server binding.
	AuthBaseURL string

	// SSO / external IdP. When SSOEnabled, the config gains an auth.idp block
	// (Google) and a freshly generated id_signing key (mirrors
	// config/local-sso.yaml).
	SSOEnabled      bool
	SSOClientID     string
	SSOClientSecret string

	// IDSigning is the ES256 key the platform signs its own ID tokens with. The
	// PEM is generated by FillSecrets when SSOEnabled.
	IDSigningKID    string
	IDSigningKeyPEM string

	// Generated secrets, populated by FillSecrets before rendering. Never
	// prompted for; always freshly generated so installs are secure by default.
	//
	// On a reinstall over an existing config or its uninstall backup, ReuseSecrets
	// pre-seeds these fields so FillSecrets (fill-only-empty) leaves them alone
	// and the config's on-disk data stays readable across the rewrite.
	EncryptionKey      string
	AdminJWTSecret     string
	AdminInvitePepper  string
	ConnectStateSecret string

	// EncryptionKeyset is a verbatim carry-over of an existing config's
	// `credentials.encryption` block, populated by ReuseSecrets on a reinstall.
	// When non-nil, render.go writes it out unchanged; EncryptionKey is
	// ignored. Preserves a hand-rotated multi-key keyset (active_id: v2 +
	// v1/v2 entries) — flattening it back to a single v1 entry would silently
	// invalidate rows encrypted with a retired key on the next rotation. Nil
	// on a fresh install; render.go emits the current default single-v1
	// layout from EncryptionKey in that case.
	EncryptionKeyset *encryptionOut

	// Telemetry consent decision, stamped onto the draft by the install command
	// (from the consent prompt) before rendering. When TelemetryEnabled is true
	// a stable opaque TelemetryInstanceID is generated and both are written into
	// the generated jentic-one.yaml so the backend's telemetry gate actually
	// reflects the user's choice. When false the config still carries an explicit
	// `enabled: false` so the decision is recorded rather than left absent.
	TelemetryEnabled    bool
	TelemetryInstanceID string

	// VenvPython is the interpreter path of the venv built for the local path.
	// Set after a successful build; when present the next-step commands use it
	// directly instead of `make install` + `uv run`.
	VenvPython string

	// MigrationsDone reports whether the wizard already applied migrations. When
	// true the next steps skip the migrate command and only cover starting the app.
	MigrationsDone bool

	// App background-start results (local path). When AppStarted is true the
	// wizard launched the app for you and the summary shows how to view/stop it.
	AppStarted bool
	AppPID     int

	// BrokerStarted / BrokerPID mirror AppStarted/AppPID for the broker process
	// launched in the background on the local (source) path.
	BrokerStarted bool
	BrokerPID     int

	// ComposePath is the generated docker-compose file path (Docker path only).
	// Set after the compose artifacts are written so the summary can point at it.
	ComposePath string
}

// NewDraft returns a Draft pre-populated with sensible local-development
// defaults (mirroring config/local.yaml).
func NewDraft() *Draft {
	return &Draft{
		RuntimePath:     RuntimeDocker,
		DBBackend:       BackendPostgres,
		PGHost:          "localhost",
		PGPort:          "5432",
		PGName:          "jentic",
		PGUser:          "postgres",
		PGPassword:      "postgres",
		SQLiteDir:       ".data",
		Apps:            []string{"registry", "admin", "control", "auth"},
		ServerHost:      "127.0.0.1",
		ServerPort:      "8000",
		BrokerPort:      DefaultBrokerPort,
		Debug:           true,
		LogLevel:        "DEBUG",
		LogFileEnabled:  true,
		LogFileDir:      ".jentic/logs",
		LogFileName:     "app.jsonl",
		MetricsExporter: "none",
		TracingExporter: "none",
	}
}

// IsPostgres reports whether the Postgres backend was chosen.
func (d *Draft) IsPostgres() bool { return d.DBBackend == BackendPostgres }

// IsDocker reports whether the containerized runtime path was chosen.
func (d *Draft) IsDocker() bool { return d.RuntimePath == RuntimeDocker }

// BaseURL is the canonical control-plane URL derived from the server binding.
// A 0.0.0.0 bind is reported as 127.0.0.1 since that is the reachable address.
func (d *Draft) BaseURL() string {
	host := d.ServerHost
	if host == "" || host == "0.0.0.0" {
		host = "127.0.0.1"
	}
	port := d.ServerPort
	if port == "" {
		port = "8000"
	}
	return "http://" + host + ":" + port
}

// BrokerURL is the local URL the broker service listens on, derived from the
// server bind host and the dedicated broker port.
func (d *Draft) BrokerURL() string {
	host := d.ServerHost
	if host == "" || host == "0.0.0.0" {
		host = "127.0.0.1"
	}
	port := d.BrokerPort
	if port == "" {
		port = DefaultBrokerPort
	}
	return "http://" + host + ":" + port
}

// CanonicalBaseURL is the auth canonical_base_url: the explicit override when
// set, otherwise the URL derived from the server binding.
func (d *Draft) CanonicalBaseURL() string {
	if d.AuthBaseURL != "" {
		return d.AuthBaseURL
	}
	return d.BaseURL()
}

// OAuthCallbackURL returns the redirect URI for the direct_oauth2 credential
// provider, derived from the canonical base URL and the control surface callback path.
func (d *Draft) OAuthCallbackURL() string {
	return d.CanonicalBaseURL() + "/credentials/oauth/callback"
}
