package install

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// unmarshalConfig renders the draft and parses it back into a generic map so
// tests can assert on structure without pinning exact byte output.
func renderToMap(t *testing.T, d *Draft) map[string]any {
	t.Helper()
	data, err := d.Render()
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.HasPrefix(string(data), "# Generated by 'jenticctl install'.") {
		t.Errorf("missing generated header")
	}
	var out map[string]any
	if err := yaml.Unmarshal(data, &out); err != nil {
		t.Fatalf("unmarshal rendered config: %v", err)
	}
	return out
}

func TestRenderSQLite(t *testing.T) {
	d := NewDraft()
	d.DBBackend = BackendSQLite
	d.SQLiteDir = "/data"
	out := renderToMap(t, d)

	dbs := out["databases"].(map[string]any)
	reg := dbs["registry"].(map[string]any)
	if reg["backend"] != "sqlite" {
		t.Errorf("registry backend = %v", reg["backend"])
	}
	if reg["path"] != "/data/registry.db" {
		t.Errorf("registry path = %v", reg["path"])
	}
	// Lexical search block is emitted for every backend.
	if _, ok := out["search"]; !ok {
		t.Errorf("expected search block for sqlite")
	}
	// No SSO by default: auth has no idp.
	auth := out["auth"].(map[string]any)
	if _, ok := auth["idp"]; ok {
		t.Errorf("did not expect idp block without SSO")
	}
}

func TestRenderPostgres(t *testing.T) {
	d := NewDraft()
	d.RuntimePath = RuntimeSource
	d.DBBackend = BackendPostgres
	d.PGHost = "db"
	d.PGPort = "5433"
	out := renderToMap(t, d)

	dbs := out["databases"].(map[string]any)
	control := dbs["control"].(map[string]any)
	if control["host"] != "db" {
		t.Errorf("control host = %v", control["host"])
	}
	if control["port"] != 5433 {
		t.Errorf("control port = %v (want int 5433)", control["port"])
	}
	if control["schema_name"] != "control" {
		t.Errorf("control schema_name = %v", control["schema_name"])
	}
	// Lexical search block is emitted for every backend.
	if _, ok := out["search"]; !ok {
		t.Errorf("expected search block for postgres")
	}
}

func TestRenderDockerSQLiteUsesContainerPaths(t *testing.T) {
	d := NewDraft()
	d.DBBackend = BackendSQLite
	d.RuntimePath = RuntimeDocker
	d.SQLiteDir = "/home/u/.jentic/data" // host dir, ignored under Docker
	out := renderToMap(t, d)

	dbs := out["databases"].(map[string]any)
	reg := dbs["registry"].(map[string]any)
	if reg["path"] != "/data/registry.db" {
		t.Errorf("docker sqlite path = %v, want /data/registry.db", reg["path"])
	}
	server := out["server"].(map[string]any)
	if server["host"] != "0.0.0.0" {
		t.Errorf("docker server host = %v, want 0.0.0.0", server["host"])
	}
	logging := out["logging"].(map[string]any)
	if logging["file_dir"] != "/logs" {
		t.Errorf("docker logging file_dir = %v, want /logs", logging["file_dir"])
	}
}

func TestRenderDockerPostgresUsesServiceHost(t *testing.T) {
	d := NewDraft()
	d.RuntimePath = RuntimeDocker
	d.DBBackend = BackendPostgres
	d.PGHost = "localhost" // ignored under Docker
	d.PGPort = "55432"     // published to the host, not used in-network
	out := renderToMap(t, d)

	dbs := out["databases"].(map[string]any)
	control := dbs["control"].(map[string]any)
	if control["host"] != "db" {
		t.Errorf("docker postgres host = %v, want db", control["host"])
	}
	if control["port"] != 5432 {
		t.Errorf("docker postgres port = %v, want in-network 5432", control["port"])
	}
}

func TestRenderSSO(t *testing.T) {
	d := NewDraft()
	d.SSOEnabled = true
	d.SSOClientID = "client-123"
	d.SSOClientSecret = "secret-abc"
	if err := d.FillSecrets(); err != nil {
		t.Fatalf("FillSecrets: %v", err)
	}
	out := renderToMap(t, d)

	auth := out["auth"].(map[string]any)
	idp, ok := auth["idp"].(map[string]any)
	if !ok {
		t.Fatalf("expected idp block when SSO enabled")
	}
	if idp["provider"] != "google" || idp["client_id"] != "client-123" {
		t.Errorf("unexpected idp: %+v", idp)
	}
	if idp["issuer"] != "https://accounts.google.com" {
		t.Errorf("idp issuer = %v", idp["issuer"])
	}
	signing, ok := auth["id_signing"].([]any)
	if !ok || len(signing) != 1 {
		t.Fatalf("expected one id_signing entry, got %v", auth["id_signing"])
	}
	entry := signing[0].(map[string]any)
	if !strings.Contains(entry["private_key_pem"].(string), "BEGIN PRIVATE KEY") {
		t.Errorf("id_signing key not a PEM: %v", entry["private_key_pem"])
	}
}

func TestRenderLoggingEnabled(t *testing.T) {
	d := NewDraft()
	d.RuntimePath = RuntimeSource
	d.LogFileEnabled = true
	d.LogFileDir = "/home/u/.jentic/logs"
	d.LogFileName = "app.jsonl"
	out := renderToMap(t, d)

	logging, ok := out["logging"].(map[string]any)
	if !ok {
		t.Fatalf("expected logging block when file sink enabled")
	}
	if logging["file_enabled"] != true {
		t.Errorf("file_enabled = %v", logging["file_enabled"])
	}
	if logging["file_dir"] != "/home/u/.jentic/logs" {
		t.Errorf("file_dir = %v", logging["file_dir"])
	}
	if logging["file_name"] != "app.jsonl" {
		t.Errorf("file_name = %v", logging["file_name"])
	}
}

func TestRenderLoggingDisabledOmitsBlock(t *testing.T) {
	d := NewDraft()
	d.LogFileEnabled = false
	out := renderToMap(t, d)
	if _, ok := out["logging"]; ok {
		t.Errorf("logging block should be omitted when the file sink is disabled")
	}
}

func TestRenderLoggingDefaultsWhenFieldsBlank(t *testing.T) {
	d := NewDraft()
	d.RuntimePath = RuntimeSource
	d.LogFileEnabled = true
	d.LogFileDir = ""
	d.LogFileName = ""
	out := renderToMap(t, d)
	logging := out["logging"].(map[string]any)
	if logging["file_dir"] != ".jentic/logs" {
		t.Errorf("default file_dir = %v", logging["file_dir"])
	}
	if logging["file_name"] != "app.jsonl" {
		t.Errorf("default file_name = %v", logging["file_name"])
	}
}

func TestRenderDirectOAuth2Provider(t *testing.T) {
	d := NewDraft()
	out := renderToMap(t, d)

	creds := out["credentials"].(map[string]any)
	providers := creds["providers"].(map[string]any)
	oauth2 := providers["direct_oauth2"].(map[string]any)
	if oauth2["kind"] != "direct_oauth2" {
		t.Errorf("kind = %v, want direct_oauth2", oauth2["kind"])
	}
	if oauth2["redirect_uri"] != "http://127.0.0.1:8000/credentials/oauth/callback" {
		t.Errorf("redirect_uri = %v, want http://127.0.0.1:8000/credentials/oauth/callback", oauth2["redirect_uri"])
	}
}

func TestRenderDirectOAuth2ProviderCustomBaseURL(t *testing.T) {
	d := NewDraft()
	d.AuthBaseURL = "https://app.example.com"
	out := renderToMap(t, d)

	creds := out["credentials"].(map[string]any)
	providers := creds["providers"].(map[string]any)
	oauth2 := providers["direct_oauth2"].(map[string]any)
	if oauth2["redirect_uri"] != "https://app.example.com/credentials/oauth/callback" {
		t.Errorf("redirect_uri = %v, want https://app.example.com/credentials/oauth/callback", oauth2["redirect_uri"])
	}
}

func TestRenderSecretsPlumbed(t *testing.T) {
	d := NewDraft()
	if err := d.FillSecrets(); err != nil {
		t.Fatalf("FillSecrets: %v", err)
	}
	out := renderToMap(t, d)
	creds := out["credentials"].(map[string]any)
	enc := creds["encryption"].(map[string]any)
	entries := enc["entries"].([]any)
	first := entries[0].(map[string]any)
	if first["material"] != d.EncryptionKey {
		t.Errorf("encryption material not plumbed through")
	}
}

func TestRenderTelemetryDefaultsOff(t *testing.T) {
	// A draft with no consent stamped renders an explicit `enabled: false` and no
	// instance_id — so the backend gate is OFF and the decision is recorded, not
	// left absent.
	out := renderToMap(t, NewDraft())
	tel, ok := out["telemetry"].(map[string]any)
	if !ok {
		t.Fatalf("expected a telemetry block, got %v", out["telemetry"])
	}
	if tel["enabled"] != false {
		t.Errorf("telemetry.enabled = %v, want false", tel["enabled"])
	}
	if _, ok := tel["instance_id"]; ok {
		t.Errorf("did not expect instance_id when telemetry is off, got %v", tel["instance_id"])
	}
}

func TestRenderTelemetryOptedIn(t *testing.T) {
	// An opted-in draft carries enabled:true plus the generated instance id, so
	// the running app reads the consent decision from jentic-one.yaml.
	d := NewDraft()
	d.TelemetryEnabled = true
	d.TelemetryInstanceID = "inst-abc-123"
	out := renderToMap(t, d)
	tel := out["telemetry"].(map[string]any)
	if tel["enabled"] != true {
		t.Errorf("telemetry.enabled = %v, want true", tel["enabled"])
	}
	if tel["instance_id"] != "inst-abc-123" {
		t.Errorf("telemetry.instance_id = %v, want inst-abc-123", tel["instance_id"])
	}
}

func TestRenderEncryptionKeysetOverrideWritesVerbatim(t *testing.T) {
	// On a reinstall ReuseSecrets pre-seeds Draft.EncryptionKeyset with the
	// existing config's keyset verbatim. Render must write that block
	// unchanged (so a hand-rotated multi-key keyset survives) and ignore
	// EncryptionKey. Flattening back to a single v1 entry would silently
	// invalidate rows encrypted under a retired key.
	d := NewDraft()
	d.EncryptionKey = "should-be-ignored"
	d.EncryptionKeyset = &encryptionOut{
		ActiveID: "v2",
		Entries: []encryptionEntryOut{
			{ID: "v1", Material: "old-material"},
			{ID: "v2", Material: "new-material"},
		},
	}
	if err := d.FillSecrets(); err != nil {
		t.Fatalf("FillSecrets: %v", err)
	}

	out := renderToMap(t, d)
	enc := out["credentials"].(map[string]any)["encryption"].(map[string]any)
	if enc["active_id"] != "v2" {
		t.Errorf("active_id = %v, want v2", enc["active_id"])
	}
	entries := enc["entries"].([]any)
	if len(entries) != 2 {
		t.Fatalf("entries len = %d, want 2", len(entries))
	}
	if entries[0].(map[string]any)["id"] != "v1" ||
		entries[0].(map[string]any)["material"] != "old-material" {
		t.Errorf("entry[0] not preserved: %v", entries[0])
	}
	if entries[1].(map[string]any)["id"] != "v2" ||
		entries[1].(map[string]any)["material"] != "new-material" {
		t.Errorf("entry[1] not preserved: %v", entries[1])
	}
}
