// reuse.go — populate a Draft with secrets from an existing jentic-one.yaml
// so a reinstall over live data keeps encrypted credentials readable.
//
// The install wizard writes a fresh config every run. If the deployment's
// database (Docker volume, or ~/.jentic/data for a local install) survives
// the reinstall, the rewritten config's freshly random encryption key can't
// decrypt rows that were encrypted with the previous run's key — the app
// then answers `execute` with an opaque 500 (`InvalidTag` /
// `DecryptionError` at `shared/crypto/encryption.py`). The same problem
// applies (with different blast radius) to the JWT secret, invite pepper,
// OAuth connect state secret, SSO signing key, and the stable telemetry
// instance id.
//
// ReuseSecrets loads the existing YAML config and copies just those
// fields onto the draft; wizard-owned settings (ports, backend, surfaces,
// etc.) stay under the wizard's control since the operator may legitimately
// be changing them.

package install

import (
	"errors"
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// reuseConfigView captures only the blocks ReuseSecrets cares about. The
// yaml tags mirror render.go's output structs so it decodes any config
// generated by a prior install; extra fields (databases, server, etc.) are
// ignored by the decoder rather than clobbering the wizard's choices.
type reuseConfigView struct {
	Auth        reuseAuthView        `yaml:"auth"`
	Admin       reuseAdminView       `yaml:"admin"`
	Credentials reuseCredentialsView `yaml:"credentials"`
	Telemetry   reuseTelemetryView   `yaml:"telemetry"`
}

type reuseAuthView struct {
	IDSigning []idSigningOut `yaml:"id_signing"`
}

type reuseAdminView struct {
	Auth   reuseAdminAuthView   `yaml:"auth"`
	Invite reuseAdminInviteView `yaml:"invite"`
}

type reuseAdminAuthView struct {
	JWTSecret string `yaml:"jwt_secret"`
}

type reuseAdminInviteView struct {
	Pepper string `yaml:"pepper"`
}

type reuseCredentialsView struct {
	Encryption encryptionOut    `yaml:"encryption"`
	Connect    reuseConnectView `yaml:"connect"`
}

type reuseConnectView struct {
	StateSecret string `yaml:"state_secret"`
}

type reuseTelemetryView struct {
	InstanceID string `yaml:"instance_id"`
}

// ReuseSecrets loads path (an existing jentic-one.yaml, or its uninstall
// backup) and pre-seeds d with its secret fields. Returns true iff at least
// one field was populated — the caller uses that to gate the operator notice.
//
// A missing file returns (false, nil): a fresh install has nothing to reuse.
// A malformed file returns (false, err) without mutating d: the caller
// should warn and continue with fresh secrets so an aborted/half-written
// prior install doesn't brick this one.
func ReuseSecrets(d *Draft, path string) (bool, error) {
	data, err := os.ReadFile(path) //nolint:gosec // path is the operator-owned install config location; reading it is the point.
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return false, nil
		}
		return false, fmt.Errorf("read %s: %w", path, err)
	}

	var view reuseConfigView
	if err := yaml.Unmarshal(data, &view); err != nil {
		return false, fmt.Errorf("parse %s: %w", path, err)
	}

	reused := false

	// Encryption keyset: preserve the whole block verbatim. A hand-rotated
	// multi-key keyset (active_id: v2 + v1/v2 entries) must survive; only
	// carry it over when it looks real (has at least one non-empty entry) so
	// an empty/malformed prior config doesn't wipe the fresh default.
	if len(view.Credentials.Encryption.Entries) > 0 {
		nonEmpty := false
		for _, e := range view.Credentials.Encryption.Entries {
			if e.ID != "" && e.Material != "" {
				nonEmpty = true
				break
			}
		}
		if nonEmpty {
			ks := view.Credentials.Encryption
			d.EncryptionKeyset = &ks
			reused = true
		}
	}

	if s := view.Admin.Auth.JWTSecret; s != "" {
		d.AdminJWTSecret = s
		reused = true
	}
	if s := view.Admin.Invite.Pepper; s != "" {
		d.AdminInvitePepper = s
		reused = true
	}
	if s := view.Credentials.Connect.StateSecret; s != "" {
		d.ConnectStateSecret = s
		reused = true
	}

	// SSO id_signing: only the first entry (render.go emits one). Kid + PEM
	// carry over so signed ID tokens don't get orphaned if the operator
	// re-enables SSO. When SSO stays disabled in the wizard the fields are
	// ignored at render time (authOut only emits them behind d.SSOEnabled).
	if len(view.Auth.IDSigning) > 0 {
		s := view.Auth.IDSigning[0]
		if s.KID != "" {
			d.IDSigningKID = s.KID
			reused = true
		}
		if s.PrivateKeyPEM != "" {
			d.IDSigningKeyPEM = s.PrivateKeyPEM
			reused = true
		}
	}

	// Telemetry instance id: only carry over when the operator re-consents.
	// The install command stamps TelemetryEnabled after the consent gate
	// (install.go), then renders. Preseeding the instance id here means
	// consenting again reuses the same opaque id (its stability contract);
	// opting out leaves TelemetryInstanceID unread at render.
	if s := view.Telemetry.InstanceID; s != "" {
		d.TelemetryInstanceID = s
		reused = true
	}

	return reused, nil
}
