package mcpcfg

// toml.go splices our server entry into Codex's `~/.codex/config.toml` as a
// clearly-marked managed block (mirroring skillgen's AGENTS.md splice): TOML
// carries comments and hand-tuned formatting we must not normalize away, so
// unlike the JSON targets the merge is textual — everything outside our
// BEGIN/END markers round-trips byte-identical.

import (
	"errors"
	"fmt"
	"strings"
)

// Managed-block sentinels for the Codex TOML entry. TOML comments, so the
// file stays valid for every parser.
const (
	tomlBeginMarker = "# BEGIN JENTIC MANAGED MCP (do not edit inside; regenerated by Jentic)"
	tomlEndMarker   = "# END JENTIC MANAGED MCP"
)

// codexTable is the TOML table Codex reads our server entry from.
const codexTable = "[mcp_servers." + ServerName + "]"

// renderCodexBlock renders the managed block body (markers included).
func renderCodexBlock(entry Entry) string {
	var b strings.Builder
	b.WriteString(tomlBeginMarker + "\n")
	b.WriteString(codexTable + "\n")
	fmt.Fprintf(&b, "command = %s\n", tomlString(entry.Command))
	b.WriteString("args = [")
	for i, a := range entry.Args {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(tomlString(a))
	}
	b.WriteString("]\n")
	b.WriteString(tomlEndMarker)
	return b.String()
}

// tomlString renders s as a TOML basic string. The values we write (an
// absolute path, fixed argv words, a ValidName-charset context name) never
// need more than quote/backslash escaping, but escape defensively anyway.
func tomlString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

// MergeCodexTOML splices the managed `[mcp_servers.jentic]` block into
// existing (nil/empty for a new file), replacing a previous managed block in
// place and appending after the existing content otherwise. It returns the
// new file bytes and whether they changed.
//
// A `[mcp_servers.jentic]` table OUTSIDE our markers is refused: TOML rejects
// duplicate tables, so writing our block alongside a hand-written entry would
// corrupt the whole Codex config. The caller reports it and leaves the file
// alone (the operator already wired jentic up by hand).
func MergeCodexTOML(existing []byte, entry Entry) (out []byte, changed bool, err error) {
	content := normalizeNewlines(string(existing))
	block := renderCodexBlock(entry)

	begin := lineAnchoredIndex(content, tomlBeginMarker)
	if begin < 0 {
		if lineAnchoredIndex(content, codexTable) >= 0 {
			return nil, false, fmt.Errorf(
				"%s already defines %s outside the jentic-managed block — leaving it untouched (remove the manual entry to let jentic manage it)",
				"config.toml", codexTable)
		}
		trimmed := strings.TrimRight(content, "\n")
		if trimmed == "" {
			return []byte(block + "\n"), true, nil
		}
		return []byte(trimmed + "\n\n" + block + "\n"), true, nil
	}

	relEnd := lineAnchoredIndex(content[begin:], tomlEndMarker)
	if relEnd < 0 {
		return nil, false, errors.New("config.toml has a jentic BEGIN marker but no END marker — fix the file by hand")
	}
	endPos := begin + relEnd + len(tomlEndMarker)

	// A duplicate table outside the managed region still corrupts the file
	// once we (re-)write ours — check the remainder too.
	outside := content[:begin] + content[endPos:]
	if lineAnchoredIndex(outside, codexTable) >= 0 {
		return nil, false, fmt.Errorf(
			"%s defines %s both inside and outside the jentic-managed block — remove the manual entry",
			"config.toml", codexTable)
	}

	next := content[:begin] + block + content[endPos:]
	if next == content && string(existing) == content {
		return existing, false, nil
	}
	return []byte(next), next != string(existing), nil
}

// normalizeNewlines collapses CRLF/CR to LF so marker matching and splicing
// behave identically regardless of how an editor saved the file.
func normalizeNewlines(s string) string {
	if !strings.ContainsRune(s, '\r') {
		return s
	}
	return strings.ReplaceAll(strings.ReplaceAll(s, "\r\n", "\n"), "\r", "\n")
}

// lineAnchoredIndex returns the byte offset of the first occurrence of marker
// that begins a line (offset 0 or immediately after '\n'), or -1. Line
// anchoring keeps a marker quoted inside a TOML string from matching.
func lineAnchoredIndex(s, marker string) int {
	from := 0
	for {
		i := strings.Index(s[from:], marker)
		if i < 0 {
			return -1
		}
		abs := from + i
		if abs == 0 || s[abs-1] == '\n' {
			return abs
		}
		from = abs + 1
	}
}
